name = "MultiobjectiveNonlinearCG"
uuid = "f1b1ba56-2df8-484c-8748-ecdea8f0f22b"
authors = ["Manuel Berkemeier <manuelbb@mail.uni-paderborn.de> and contributors"]
version = "0.0.1-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Parameters = "0.12"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
